# Generated by Django 6.0.3 on 2026-03-20 09:29

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biography', models.TextField(blank=True, max_length=1500)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(help_text='Format: 10 or 13 digits', max_length=13, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_isbn', message='The ISBN must contain exactly 10 or 13 digits.', regex='^(?:\\d{10}|\\d{13})$')], verbose_name='ISBN')),
                ('language', models.CharField(max_length=2)),
                ('pages', models.PositiveIntegerField()),
                ('published', models.DateTimeField(verbose_name='Date published')),
                ('resume', models.TextField(blank=True, max_length=1500)),
                ('title', models.CharField(max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.author')),
                ('library', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.library')),
            ],
        ),
    ]
