# Generated by Django 6.0.3 on 2026-03-20 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='biography',
            field=models.TextField(blank=True, help_text='Write a short presentation in a maximum of 1500 characters.', max_length=1500, null=True, validators=[django.core.validators.MaxLengthValidator(1500)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='resume',
            field=models.TextField(blank=True, help_text='Describe the work in a maximum of 1500 characters.', max_length=1500, null=True, validators=[django.core.validators.MaxLengthValidator(1500)]),
        ),
    ]
