# Generated by Django 6.0.3 on 2026-03-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
