# Generated by Django 6.0.3 on 2026-03-20 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_firstname_author_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(blank=True, null=True, verbose_name='Date published'),
        ),
    ]
