# Generated by Django 6.0.3 on 2026-04-10 00:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_book_cover_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
